services:
  db:
    image: postgres:14
    container_name: product_postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=product_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5435:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    container_name: product_migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["./server"]